sudo: required
services:
  - docker

before_install:
  - docker build -t tarunfy/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true tarunfy/react-test npm run test

after_success:
  - docker build -t tarunfy/multi-client ./client
  - docker build -t tarunfy/multi-nginx ./nginx
  - docker build -t tarunfy/multi-server ./server
  - docker build -t tarunfy/multi-worker ./worker
